### ISSUE TITLE
How to test transition arguments in onEntry?

### ISSUE THREAD

**Issue by phfeustel** [KStateMachine/kstatemachine#105]
In my current implementation, I'm using a [transition argument](https://kstatemachine.github.io/kstatemachine/pages/transitions/transitions.html#transition-argument) to pass some data to the `second` state. 

In the `second` state, I'm accessing the data via:
```kotlin
onEntry {
                val myData = it.transition.argument as MyData
}
```

In my test, I'm using 
```kotlin
machine.startFromBlocking(state = second, argument = myData)
```

Debugging the test, it shows that `myData` does not end up in `it.transition.argument` but in `it.argument`, which leads to a failing test.

I tracked it down to [`makeStartTranisitionParams`](https://github.com/KStateMachine/kstatemachine/blob/5f07bf4f850ee99630588b4bb03d24c5abac6337/kstatemachine/src/commonMain/kotlin/ru/nsk/kstatemachine/statemachine/StateMachineImpl.kt#L405) is not setting the argument in the `Transition` but just in the `TransitionParams`.

Do you have any advise on a proper test setup to test `onEntry` with a transition argument?

**Comment by nsk90** [comment]
Hello, looks that due to using using of `startFrom` transition argument is never set by your production code. Yes as you correctly mentioned Event argument and Transition argument, are different types of arguments and they are not related to each other.

In a test you can get your transition reference by `findTransition/requireTransition` APIs https://github.com/KStateMachine/kstatemachine/blob/master/kstatemachine/src/commonMain/kotlin/ru/nsk/kstatemachine/state/TransitionStateApi.kt#L38

And set it's argument explicitly in test code.

Alternatively you can run the StateMachine from some earlier State, to process necessary Event in the test, to trigger your production code that sets the transition argument.

I cannot suggest something better than that.

**Comment by phfeustel** [comment]
Thank you very much for the hint!

In my test, I'm using now 
```kotlin
machine.findTransition<StartEvent>()?.argument = myData
```
which works out fine!

**Comment by nsk90** [comment]
For test code I recommend using "require" version, to end up with exception if the transition will not be found. Using "find" + "?" which is effectively "if" may make the test false positive. 🤓

**Comment by phfeustel** [comment]
Thanks for the clarification. 

In my specific case I was not problem, because the transition argument would then still be `null`. But `requireTransition` is the more solid approach to let the test fail early and in all cases.
